<?php

namespace App\Services\Reports;

use App\Services\Reports\Support\TableReport;
use Symfony\Component\HttpFoundation\ResponseHeaderBag;
use Symfony\Component\HttpFoundation\StreamedResponse;

class CsvTableExporter
{
    public function download(TableReport $report): StreamedResponse
    {
        $filename = sprintf(
            '%s-%s.csv',
            $report->filenameBase,
            $report->generatedAt->format('Y-m-d-His'),
        );

        return response()->streamDownload(function () use ($report): void {
            $handle = fopen('php://output', 'wb');

            if ($handle === false) {
                return;
            }

            fwrite($handle, "\xEF\xBB\xBF");

            fputcsv($handle, [$report->title]);
            fputcsv($handle, ['Generated at', $report->generatedAt->format('Y-m-d H:i:s T')]);
            fputcsv($handle, ['Generated by', $report->generatedBy]);

            foreach ($report->filters as $label => $value) {
                fputcsv($handle, [$label, $value]);
            }

            fputcsv($handle, []);
            fputcsv($handle, array_values($report->columns));

            foreach ($report->rows as $row) {
                $cells = [];

                foreach (array_keys($report->columns) as $key) {
                    $cells[] = (string) ($row[$key] ?? '');
                }

                fputcsv($handle, $cells);
            }

            fclose($handle);
        }, $filename, [
            'Content-Type' => 'text/csv; charset=UTF-8',
            'Content-Disposition' => (new ResponseHeaderBag)->makeDisposition(
                ResponseHeaderBag::DISPOSITION_ATTACHMENT,
                $filename,
            ),
        ]);
    }
}
