<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 11px;
            color: #111827;
            margin: 24px;
        }

        h1 {
            margin: 0 0 8px;
            font-size: 20px;
        }

        .meta,
        .filters {
            margin-bottom: 16px;
        }

        .meta p,
        .filters p {
            margin: 2px 0;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th,
        td {
            border: 1px solid #d1d5db;
            padding: 6px 8px;
            vertical-align: top;
        }

        th {
            background: #f3f4f6;
            font-weight: 700;
            text-align: left;
        }

        td {
            white-space: pre-wrap;
        }

        .muted {
            color: #4b5563;
        }
    </style>
</head>
<body>
    <h1>{{ $title }}</h1>

    <div class="meta">
        <p><strong>Generated at:</strong> {{ $generatedAt->format('Y-m-d H:i:s T') }}</p>
        <p><strong>Generated by:</strong> {{ $generatedBy }}</p>
    </div>

    <div class="filters">
        <p><strong>Filters used</strong></p>
        @foreach ($filters as $label => $value)
            <p class="muted">{{ $label }}: {{ $value }}</p>
        @endforeach
    </div>

    <table>
        <thead>
            <tr>
                @foreach ($columns as $label)
                    <th>{{ $label }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @forelse ($rows as $row)
                <tr>
                    @foreach (array_keys($columns) as $key)
                        <td>{{ $row[$key] ?? '' }}</td>
                    @endforeach
                </tr>
            @empty
                <tr>
                    <td colspan="{{ count($columns) }}">No records matched the selected filters.</td>
                </tr>
            @endforelse
        </tbody>
    </table>
</body>
</html>
